name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install deps
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Setup native modules
        run: yarn setup

      - name: Build files
        run: yarn build

      - name: Run publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
