name: Native CI

on:
  push:
    paths:
      - externals
      - src

jobs:
  lint-and-test:
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install nodejs deps
        run: yarn install --immutable --immutable-cache --check-cache

      - run: yarn setup
      - run: yarn lint
      - run: yarn prebuild
      - run: yarn build
      - run: yarn test:cpp
